### ISSUE TITLE
Cannot compile.

### ISSUE THREAD

**Issue by JamesKim2998** [modesttree/Zenject#106]
SignalBus has compilation issue.

Error is occurred at the line below.
https://github.com/svermeulen/Extenject/blob/6fbb4481375645ad888614bfe69173e5926ba703/UnityProject/Assets/Plugins/Zenject/OptionalExtras/Signals/Main/SignalBus.cs#L68

Thanks.

**Comment by Extrys** [comment]
I will fix it in a few moments

**Comment by Mathijs-Bakker** [comment]
This is a known issue. I was reverting the last merges as the CI returns build errors and some tests are failing. 
It will take a few days before I will address this and notify some people about this.
Corona is keeping me occupied.

**Comment by Extrys** [comment]
> This is a known issue. I was reverting the last merges as the CI returns build errors and some tests are failing.
> It will take a few days before I will address this and notify some people about this.
> Corona is keeping me occupied.

I just fixed it with #108
