### ISSUE TITLE
Signal - SubscribeOnce

### ISSUE THREAD

**Issue by cpetry** [modesttree/Zenject#109]
I would like to subscribe once with an action to a signal.
Once this signal was fired, it should be unsubscribed automatically.

Is this currently possible?

> "This message will destroy itself in 3,2,1..." :D

**Comment by Extrys** [comment]
yes you can, you just have to dispose the signal itself in the subscription via Composite disposables for example

**Comment by cpetry** [comment]
In fact I don't need a self destructing signal but a self unsubscribing subscription (thursday evening I didn't wrap my head around it correctly...)

Found it!
Searching the code itself for an idea I stumbled upon a comment:

> This is a weird check for the very rare case where an Unsubscribe is called
> from within the same callback (see TestSignalsAdvanced.TestSubscribeUnsubscribeInsideHandler)

In there I found a great example of what I needed!
```
Action handler4 = null;
handler4 = () =>
{
    received = true;
    signalBus.Unsubscribe<FooSignal>(handler4);
};
signalBus.Subscribe<FooSignal>(handler4);
```
Thanks!
