### ISSUE TITLE
The binding "Ctrl+Shift+R" conflicts with multiple commands

### ISSUE THREAD

**Issue by develax** [modesttree/Zenject#133]
**Screenshots**
![image](https://user-images.githubusercontent.com/13222593/81235492-b4275680-9003-11ea-85ed-227c512f2a99.png)

**Extenject and Unity info (please complete the following information):**
 - Zenject version: 9.1.0
 - Unity version: 2019.3.10f

**Comment by Mathijs-Bakker** [comment]
I checked it, and you're right.
