### ISSUE TITLE
NSubstitute.dll in AutoSubstitute.zip generates a build warning

### ISSUE THREAD

**Issue by Maesla** [modesttree/Zenject#144]
**Describe the bug**
Nsubstitute dll included in the zip AutoSubstitute.zip generates a warning when compiling the project and adds 10 MB in dlls to the build

**To Reproduce**
Extract AutoSubstitute.zip and build the project

**Expected behavior**
No build warnings
No additional size to the build

**Screenshots**
Using Build Report Inspector:
With NSubstitute.dll
![imagen](https://user-images.githubusercontent.com/25863696/82804034-d2090e00-9e81-11ea-86ef-b2b74da406f7.png)
Without NSustitute.dll
![imagen](https://user-images.githubusercontent.com/25863696/82804082-ea792880-9e81-11ea-8103-8a47722acd0e.png)

**Extenject and Unity info (please complete the following information):**
 - Zenject version:9.1.0
 - Unity version:2019.3.6f1
 - Project's scripting backend [e.g. Mono/IL2CPP]: Mono

**Additional context**
The NSubstitute.dll is 2.0.3.

I have tested with this version:
https://github.com/thinkuldeep/NSubstituteUnity, that I think is 4.3.0, but I'm not sure, and everything works.

A minor issue is that verion of NSubstitute has dependencies, but are included in that package

**Comment by Mathijs-Bakker** [comment]
You can use any working NSubstitute library.

Just make sure you put it in a folder called **Editor**. So it will be excluded in runtime/build.

**Comment by Maesla** [comment]
Ok, I thought I can use in Build Tests.

Anyway I changed to a newer NSubstitute version and it is working.

Thank you
