### ISSUE TITLE
Sometimes the Project Context is not loaded Unity 2020.1.0.bxx

### ISSUE THREAD

**Issue by manuelgoellnitz** [modesttree/Zenject#152]
**Describe the bug**
Sometimes when starting play mode the project context is not loaded. 
To Fix it, you have to rename the prefab, start playmode, stop playmode, name it back to "ProjectContext", or just update the prefab somehow. The it is loaded for a while

**To Reproduce**
It is random but more frequent after updating Unity or a package

**Expected behavior**
The Project Context should be loaded everytime you go into playmode :)

**Screenshots**

**Extenject and Unity info (please complete the following information):**
 - Zenject version: 9.1.0
 - Unity version: Unity 2020.1.0.b13 (but also happened in b11 and b12)
 - Project's scripting backend [e.g. Mono/IL2CPP]: Mono

**Additional context**
-

**Comment by svermeulen** [comment]
I tried this with 2020.1.0f1 but was unable to reproduce it.  Maybe unity fixed it?   If not can you provide a minimal example?

**Comment by manuelgoellnitz** [comment]
Yea the problem is gone, since unity 2020.1 is out of beta

**Comment by svermeulen** [comment]
Ok thanks for letting us know

**Comment by manuelgoellnitz** [comment]
The problem reoccured with 2020.1.9f1.

**Comment by manuelgoellnitz** [comment]
And now it occurs not at random, but every time I startup Unity Zenject doesn't load the ProjectContext until I update it.
Happens in 2020.1.9 and later versions
