### ISSUE TITLE
List injection with duplicates

### ISSUE THREAD

**Issue by Maesla** [modesttree/Zenject#154]
**Describe the bug**
Sometimes, a List injection contains duplicated instances

**To Reproduce**
Create a Gameobject
Add a component Foo
Add a Zenject Binding Component
- In Components array, add Foo more than once

Add other component, with public List<IFoo> fooCollection;
- fooCollection.Count == 3. Foo is in the list 3 times

I attach a package with a small example.

[Bug Duplicate Instances in List Injection.zip](https://github.com/svermeulen/Extenject/files/4857351/Bug.Duplicate.Instances.in.List.Injection.zip)

Open Duplicate Inject Scene.
Play the scene.
See the error in the console

**Expected behavior**
I expected that fooCollection contains only unique elements

I attach also in the package a simple test named UniqueInjectTestSimplePasses that, strangely works as expected
**Screenshots**

**Extenject and Unity info (please complete the following information):**
 - Zenject version: 9.1.0. Branch:release-candidate. Commit: c0d8da57116dc24236af134e54041b9a53fd9e16
 - Unity version:
 - Project's scripting backend [e.g. Mono/IL2CPP]: Mono

**Additional context**
I got this problem not with Zenject Binding Component, but adding the same instance from two installers by mistake.
So I thought maybe was designed like this, if you bind several times an instance, you get that instance several times in the list, but then I wrote a test and it seems to check somehow that the instances have to be unique.
![imagen](https://user-images.githubusercontent.com/25863696/86235232-6446b500-bb98-11ea-8f62-a17bd010e702.png)

So, with the test, they are unique, but with a Scene Setup, I get duplicated instances
```csharp
        [Test]
        public void UniqueInjectTestSimplePasses()
        {
            var rootContainer = new DiContainer();

            GameObject dummyGo = new GameObject("dummyGo");
            var foo = dummyGo.AddComponent<Foo>();

            string identifier = null;
            var componentType = foo.GetType();

            rootContainer.Bind(componentType.Interfaces()).WithId(identifier).FromInstance(foo);
            rootContainer.Bind(componentType.Interfaces()).WithId(identifier).FromInstance(foo);
            rootContainer.Bind(componentType.Interfaces()).WithId(identifier).FromInstance(foo);
            rootContainer.Bind(componentType.Interfaces()).WithId(identifier).FromInstance(foo);
            rootContainer.Bind(componentType.Interfaces()).WithId(identifier).FromInstance(foo);

            rootContainer.Bind<FooCollectionInjected>().FromNewComponentOnNewGameObject().OnInstantiated<FooCollectionInjected>((ctx, fooCollection) =>
            {
                //Passes
                NUnit.Framework.Assert.That(fooCollection.fooCollection, Has.Count.EqualTo(1));
                CollectionAssert.AllItemsAreUnique(fooCollection.fooCollection);
            });
        }
```

By Scene Setup
```csharp
public class FooCollectionInjected: MonoBehaviour
{
    [Inject]
    public List<IFoo> fooCollection;

    public void Start()
    {
        // Fails
        bool isUnique = fooCollection.Distinct().Count() == fooCollection.Count();
        Debug.Assert(isUnique);
    }
}
```

Thank you

**Comment by coreyjharvey** [comment]
I took a peek at this.   I think the problem is with your test and not with zenject here.  In my tests, Zenject behaves the same both for scene bindings and code bindings in terms of adding multiple instance bindings.  In both cases it results in duplicates in the list.

In your test, the OnInstantiated callback is never called, because the Resolve step is never triggered.  If you change the bottom of your test to this:

```csharp
rootContainer.Bind<FooCollectionInjected>().FromNewComponentOnNewGameObject().AsSingle().OnInstantiated<FooCollectionInjected>((ctx, fooCollection) =>
{
    NUnit.Framework.Assert.That(fooCollection.fooCollection, Has.Count.EqualTo(1));
    CollectionAssert.AllItemsAreUnique(fooCollection.fooCollection);
});

rootContainer.Resolve<FooCollectionInjected>();
```

Then it will fail, as you would expect, since fooCollection has size 5.

**Comment by Maesla** [comment]
Yes, you are absolutely right!

I will assume that if you bind twice the same instance you will get the instance twice in the list injection.

Mystery solved. Thank you.
