### ISSUE TITLE
Inject order is incorrect

### ISSUE THREAD

**Issue by emrys90** [modesttree/Zenject#162]
In a class called PlayerActor (this is a scene object), I have an inject method
        [Inject]
        public void Init(GameContext gameContext)

In my installer I have
            var gameContext = GameObject.FindObjectOfType<GameContext>();
            if (gameContext == null)
            {
                throw new System.Exception("GameContext not found in scene!");
            }

            Container.BindInstance(gameContext);

From my understanding of how this should work, GameContext should have its injection ran first because PlayerActor depends on GameContext. PlayerActor is being injected first though. How can I fix this?

**Comment by svermeulen** [comment]
You're right that Zenject should guarantee that classes injected into an inject method have themselves already been injected, unless there are circular dependencies involved.

Are GameContext and PlayActor both MonoBehaviours added to the scene?   Can you provide a minimal example showing the problem?
