### ISSUE TITLE
Test Framework and Unity Package Manager

### ISSUE THREAD

**Issue by Nezz** [modesttree/Zenject#198]
**Describe the bug**
I'm trying to move our project to include Extenject using UPM instead of a submodule. While it works well for the core code of Extenject, the `Zenject-TestFramework` assembly gets excluded by Unity, resulting in compiler errors:

```
TestFixture.cs: error CS0246: The type or namespace name 'ZenjectIntegrationTestFixture' could not be found (are you missing a using directive or an assembly reference?)
```

This is because TestFramework references NUnit and therefore is viewed as a test assembly by Unity. [This page](https://docs.unity3d.com/2019.3/Documentation/Manual/cus-tests.html) described that this behavior ban be reversed by adding the following to `manifest.json` of the project that references the package:

```
  "testables": [
    "com.svermeulen.extenject"
  ]
```

However, when this is done, not only `Zenject-TestFramework` gets included in the project, but also all the tests:
<img width="602" alt="Screenshot 2020-11-09 at 13 17 41" src="https://user-images.githubusercontent.com/431167/98534972-fcaf1d80-228d-11eb-8576-b48147077432.png">

**To Reproduce**
1. Add the package in Unity 2019.4:
```
ssh://git@github.com/svermeulen/Extenject.git?path=UnityProject/Assets/Plugins/Zenject
```
2. Try to reference code from `Zenject-TestFramework`

**Actual behavior**
Code from `Zenject-TestFramework` cannot be referenced unless the testables attribute is added to `manifest.json`, which then also imports all the tests for Extenject.

**Expected behavior**
Code from `Zenject-TestFramework` can be referenced without importing tests for Extenject.

**Extenject and Unity info (please complete the following information):**
 - Zenject version: Latest of master
 - Unity version: 2019.4.13

**Comment by Nezz** [comment]
A solution I'd propose is to separate Extenject into multiple packages. This would involve the following changes:
1. Change current `package.json` to only include the Extenject core code (all the things currently not in OptionalExtras) and its tests.
2. Create individual packages for OptionalExtras: MemoryPoolMonitor, ReflectionBaking, Signals, TestFramework
3. Move samples from OptionalExtras to [Samples in Packages](https://forum.unity.com/threads/samples-in-packages-manual-setup.623080/) in the core package.

**Comment by dudziakl** [comment]
For anyone that is going to use this as workaround for missing Zenject-TestFramework. After modify manifest.json please do zenject package re-import and then from the import list select Zenject-TestFramework. It won't be automatically triggered by the manifest. This way you can skip import of samples, zenject's unit tests and other libraries.

**Comment by halzate93** [comment]
Hi,

I'm facing the same problem when trying to write some automated tests for a package I'm developing. I see @Nezz marked this as completed but I'm not too sure wether the approach I should keep trying is the workaround or has the test framework been split to a different package?

**Comment by Nezz** [comment]
@halzate93 This issue was fixed here:
https://github.com/Mathijs-Bakker/Extenject/commit/69705b49ff3b01f7a39f7da5fcfc072d9790f25d
Just include the package.json under the Source folder instead of the one under `UnityProject/Assets/Plugins/Zenject`.

**Comment by halzate93** [comment]
@Nezz That worked for me, thanks!
