### ISSUE TITLE
Using PreInstall/PostInstall/PreResolve/PostResolve in the ProjectContext

### ISSUE THREAD

**Issue by vizgl** [modesttree/Zenject#20]
I can't use methods PreInstall/PostInstall/PreResolve/PostResolve from the ProjectContext.
I want to make some sort of loading menu, and trying to catch event PostResolve of the ProjectContext instance. But unfortunately it can't be done, because this actions called when I call Instance method and they will never fire.

```csharp
void Main()
{
	ProjectContext.Instance.PostResolve += OnPostResolved;
}
```

**Comment by svermeulen** [comment]
Yeah you're right. I've fixed it now by making those events static so you can access it by calling `ProjectContext.PostResolve` etc.
