### ISSUE TITLE
[Bug] Object that has Reference to the SceneContext stay in memory after scene unloaded

### ISSUE THREAD

**Issue by sapiscow** [modesttree/Zenject#246]
Hello!

I've found that Zenject somehow is "leaking" in memory, i used the advanced project example from Zenject. Any instances that has bound to SceneContext are kept in memory even when the scene has been unloaded such as the GameInstaller and anything that used Pool. Any help to solve this issue (or find a workaround for it) would be appreciated!

Steps to reproduce:
- Use the example project from Zenject (SpaceFighter)
- Then, I just adding an empty scene with only one gameobject that contains default SceneContext, LoaderScript to load back the SpaceFighter scene, and Zenject Binding with that loader script component
- After that i do profilling from memory profile. What i do is just from SpaceFighter i go to empty scene, back to SpaceFighter scene, back again to empty scene for a few times
- Memory Profiler shows the instance of the object that i've mentioned above is increasing as much as i load the scene

Sample Project to reproduce:
[Zenject Test.zip](https://github.com/modesttree/Zenject/files/6775069/Zenject.Test.zip)

**Comment by johnfriedrich** [comment]
What editor version? We are getting an infinite Application.Reload issue after the second time entering playmode with Unity 2020.3 with our project. 2019.4 is fine. Mabe it has the same root cause

**Comment by sapiscow** [comment]
@johnfriedrich Unity 2020.3.12f1, i've fixed this issue with adding:
```csharp
private void OnDestroy()
{
    _container.UnbindAll();
}
````
in `SceneContext.cs` of Zenject.  
  
And, i also need to remove all reference manually when i injected a reference in a class (this is taking too much time).
