### ISSUE TITLE
Incorrect BindExecutionOrder Behaviour per Documentation

### ISSUE THREAD

**Issue by spreagtha** [modesttree/Zenject#25]
As per the [main documentation](https://github.com/svermeulen/Extenject#update--initialization-order) `BindExecutionOrder` and it's variants are intended to set the priority for a specified type's execution order, with the following example given:

```
void InitExecutionOrder()
{
    // In many cases you don't need to worry about execution order,
    // however sometimes it can be important
    // If for example we wanted to ensure that AsteroidManager.Initialize
    // always gets called before GameController.Initialize (and similarly for Tick)
    // Then we could do the following:
    Container.BindExecutionOrder<AsteroidManager>(-10);
    Container.BindExecutionOrder<GameController>(-20);

    // Note that they will be disposed of in the reverse order given here
}
```
The indication being that AsteroidManager having a higher priority value will always be executed first/last depending on the interface type, in the case of IInitializable/ITickable AsteroidManager should be called first before GameController. What I am seeing in my own project is the opposite, and after looking into InitializableManager the following stands out:

```
public void Initialize()
{
    //....
    _initializables = _initializables.OrderBy(x => x.Priority).ToList();

    //....
    foreach (var initializable in _initializables)
    {
        //....
        initializable.Initializable.Initialize();
        //....
    }
}
```

Since the OrderBy results are ascending, this puts AsteroidManager at the end of the list (in my project a different type of course) and so it is initialized after GameController. An easy fix would be to change the OrderBy operator to OrderByDescending, and I considered making a pull-request doing just that, but I am worried about the implications of the change for projects depending on the current execution order.

The scenarios here are:

1. The documentation and I are wrong in the assumption and the numbers are intended to be non-negative in the example given, meaning that AsteroidManager (priority +10) and GameController (priority +20) would operate as expected.
2. Other projects using BindExecutionOrder have noticed this issue as well and disregarded the documentation, using lower numbers as 'higher priority'.

The last changes seem to go back to e639debb8ccca8f70c5f37639e229686a4992dbb so I expect that at this point the accepted behaviour is that lower numbers are higher priority, but if you could clarify on this point I could put together a PR for the doc changes, and any uses in examples in the code base.

Thank you

**Comment by svermeulen** [comment]
Yes, the intention was for lower numbers are supposed to be higher priority.  So the answer is that the sample is incorrect  :)  I've fixed this by swapping the priority numbers in the sample.  Thanks for reporting this
