### ISSUE TITLE
NullReferenceException when second time inject

### ISSUE THREAD

**Issue by starock** [modesttree/Zenject#273]
Hi~ I'm new at Zenject. Here is my question:

**In installer bind the class**
`Container.Bind<AccountInfo>().AsCached(); 
`

**Inject it at classA**

```
private AccountInfo accountInfo;             

[Inject]
private void Init(GameSetup _gameSetup, AccountInfo _accountInfo)
{
    this.gameSetup = _gameSetup; 
    this.accountInfo = _accountInfo;
}

accountInfo.address = "xxx'; // works fine
```

**Then inject AccountInfo to classB**
```
private AccountInfo accountInfo;      
        
[Inject]
private void Init(AccountInfo _accountInfo)
{
    this.accountInfo = _accountInfo;
}

accountInfo.address = "xxx'; //NullReferenceException: Object reference not set to an instance of an object
```

**Why accountInfo changed to null? AsCached() dosen't work? Or something worng else?** 

**Help please~~ Thank you!**

**Comment by Mathijs-Bakker** [comment]
When a DI-framework cannot resolve an object it injects ``null``.

Most of the time it's due to the object is registered (bind) in another scope (context).
