### ISSUE TITLE
Binding through FromComponentInNewPrefab() Does not work.

### ISSUE THREAD

**Issue by eethaen** [modesttree/Zenject#28]
I am trying to bind a MonoBehaviour on a prefab through **FromComponentInNewPrefab()** in a Scenecontext. The prefab I am Instantiating already contains the MonoBehaviour I am binding. But it doesn't work. then I thought something might be wrong with the prefab then I tried **FromNewComponentOnNewGameObject()** it also didn't work.

**Comment by Mathijs-Bakker** [comment]
**.FromComponentInNewPrefab(myPrefab); instantiates and then injects all dependencies into the prefab's MonoBehaviours. It does not map MB's to the DiContainer.**

Easiest way is - on your game object/prefab - to use the Zenject Binding Component. And drag your MB's to it.

**Comment by eethaen** [comment]
Thanks for your reply, but another issue I forgot to mention in the original post is the actual GameObject is not instantiated in the scene. even in case of **FromNewComponentOnNewGameObject()**.
