### ISSUE TITLE
[Suggestion] Asset Store & Package Manager Support

### ISSUE THREAD

**Issue by schodemeiss** [modesttree/Zenject#3]
It'd be great to make Extenject support the newer Package Manager as well as the Asset Store.  Zenject never reached 8.0.0 via the Asset Store and it seems Unity themselves are shipping more and more through the Package Manager itself. If it's not possible to submit it to their managed repository there are other third-party repo's.

See https://github.com/modesttree/Zenject/issues/613#issue-416756573 as an example of a third-party repository.

**Comment by svermeulen** [comment]
I'll look into supporting the package manager properly

It was accepted into asset store today here:  https://www.assetstore.unity3d.com/#!/content/144698

So that's good at least
