### ISSUE TITLE
Project Context - ParentNewObjectsUnderSceneContext flag missing in Editor

### ISSUE THREAD

**Issue by aetsch-dev** [modesttree/Zenject#34]
From what I read in the source code and in your documentation, in the Unity Editor, the Project Context component should have a flag "Parent new objects under ProjectContext". SceneContext components have this flag and the ProjectContext's don't. Is that a bug?
I tested this in Unity 2019.1.14f and Unity 2019.2.6f.

**Comment by svermeulen** [comment]
Yep you're right, that flag wasn't exposed to the unity inspector.  Fixed now.  Thanks for reporting it
