### ISSUE TITLE
RunnableContext.CreateComponent<T> does not work on GameObjectContext

### ISSUE THREAD

**Issue by piti6** [modesttree/Zenject#41]
I think this happens cause GameObjectContext Initialize moved from Awake to Construct method which needs to inject DIContainer parentContainer.

so, now I have two choices - make subContainer manually and install installer, or call Construct method manually.

any suggested ideas?

**Comment by svermeulen** [comment]
I don't think you need to use `GameObjectContext.CreateComponent`.  You can just use `AddComponent<GameObjectContext>` and then wait for it to be injected.  When you create it dynamically, aren't you placing it in a subcontainer?   If nothing else, SceneContext container or ProjectContext container?  If so then you shouldn't need to call Construct manually and instead trigger injection on it

**Comment by piti6** [comment]
Thanks for reply.
No, AddComponent does not work either - what I want to do is create GameObject that has GameObjectContext and some of (custom) Installer completely dynamically.

> aren't you placing it in a subcontainer?

does this means I should set created GameObjectContext to the subcontainer? (in my situation, SceneContext container I guess?)

If so, how should I do?

```
public static GameObjectContext Create(DiContainer parentContainer, params Type[] installerTypes)
{
    var go = new GameObject();

    var installers = installerTypes.Select(x => go.AddComponent(x))
        .Cast<MonoInstaller>();

    var context = CreateComponent<GameObjectContext>(go); //or AddComponent
    context.Installers = installers;
    context.Construct(parentContainer);

    return context;
}
```
↑ this is what I am doing right now.

should I use Factory for GameObjectContext ?
again, thanks for the help 😄

**Comment by svermeulen** [comment]
The way you're doing it looks like it should work, but it's not how zenject is intended to be used.

Couldn't you do something like this instead?

```csharp
Container.BindFactory<Foo, Foo.Factory>().FromSubContainerResolve().ByNewGameObjectInstaller<MyRootInstaller>();

public class MyRootInstaller : Installer {
    public override void InstallBindings() {
    }
}
```

Then when you call `FooFactory.Create` I think it should result in the same thing you are doing there.  If you have multiple installers you can call them all from `MyRootInstaller`

**Comment by piti6** [comment]
Yeah, I agree with you - Construct method should be injected not calling manually.
btw, your suggested solution works like a charm. thank you! 😄
