### ISSUE TITLE
Zenject is incompatible with UNet?

### ISSUE THREAD

**Issue by subzero911** [modesttree/Zenject#43]
Seems like DI is not suitable for Unity Networking / Mirror at all.
It has NetworkManager which needs a player prefab reference. But if I spawn a player through DI bindings, I obviously can't put it into Network Manager slot.

**Comment by wlong0153** [comment]
If you're worried about being able to resolve bindings on a player prefab that is instantiated through a network manager, you can either manually resolve them or add a ZenAutoInjecter component to the prefab. If you have logic in Awake that requires those dependencies, you may need to move the auto injector component up in the script execution order.

**Comment by Mathijs-Bakker** [comment]
Closing this as it has been answered perfectly.
Thanks @wlong0153!
