### ISSUE TITLE
NSubstitute warnings with upm

### ISSUE THREAD

**Issue by paulpach** [modesttree/Zenject#60]
I imported extenject 9.1.0 using upm,  and I get the following warnings:

```
A meta data file (.meta) exists but its asset 'Packages/com.svermeulen.extenject/OptionalExtras/TestFramework/Editor/AutoSubstitute/__MACOSX/AutoSubstitute/NSubstitute' can't be found. When moving or deleting files outside of Unity, please ensure that the corresponding .meta file is moved or deleted along with it.

Couldn't delete Packages/com.svermeulen.extenject/OptionalExtras/TestFramework/Editor/AutoSubstitute/__MACOSX/AutoSubstitute/NSubstitute.meta because it's in an immutable folder.
```

**Comment by paulpach** [comment]
@starikcetin I get this warning with your fork,  using openupm

**Comment by Mathijs-Bakker** [comment]
This has also been posted here: [issue24 UPM Support](https://github.com/svermeulen/Extenject/issues/24)
I will close this one.

Note: When you delete or move a file outside of Unity you get the *meta data file* warning. Stating that you should not do these actions outside of Unity. These warnings are usually appearing only once. This is only fixable on another fork. It's probably better to raise an issue there.

**Comment by paulpach** [comment]
@Mathijs-Bakker this shows over and over  when the problem is in a upm package,  not just once.

I would have reported the issue in the fork,  but issues are disabled there,  sorry.
