### ISSUE TITLE
Automate releases

### ISSUE THREAD

**Issue by paulpach** [modesttree/Zenject#63]
This is just a suggestion:

You can see one of my repos for a good example:
https://github.com/MirrorNG/MirrorNG

I have set up github actions that automatically creates releases based on the commit log.

if I commit something with the comment "fix: whatever got fixed",  it will automatically runs unit tests, static analysis, increase the patch version,  create a github release,  publish upm branch,  create tags,  update changelog, add comments to all issues and pull requests that got released, generate and publish documentation.

What I am asking is if you are interested on this workflow,  it makes it easy to keep upm branch up to date,  all I have to do is prefix my commit messages with either "fix", "perf", "feat" or "breaking" depending on the nature of the change and it does the rest.

Your repo currently does not seem to have a CI/CD pipeline,  which means you are doing all of this yourself every single time.

**Comment by paulpach** [comment]
I can help port over some of the scripts if you are willing to adjust your workflow to this.

**Comment by Mathijs-Bakker** [comment]
Yeah! I love this!
CI/CD support is definitely lacking as running tests.
So help on this is surely welcome! @paulpach

**Comment by Mathijs-Bakker** [comment]
I was checking one of the .yml's and saw the Unity Testrunner CI support.
Didn't know of the existence as I did not seen it here on GH before.
Is it possible to set up the actions workflow on another fork and merge it in this one?
Or just create a new branch? Btw: I saw also a Unity Runner by MirrorNG in the actions marketplace.

**Comment by paulpach** [comment]
I created the action myself fairly recently.  If you looked for it a few weeks ago,  it did not exist

**Comment by paulpach** [comment]
Yeah,  you can create a branch,  get it to work and then merge it.   Best way to go about it. 

You will need to create a unity manual license and add it as a secret to your repository
