### ISSUE TITLE
warning CS0649: Field is never assigned to with [Inject] annotation

### ISSUE THREAD

**Issue by Suvitruf** [modesttree/Zenject#65]
**Version:** 9.1.0

    [Inject]
    private ResourcesController _resourcesController;

Got:

> warning CS0649: Field 'FloorStash._resourcesController' is never assigned to, and will always have its default value null

How can I fix it without `pragma` usage?

**Comment by Mathijs-Bakker** [comment]
Two options:
- csc.rsp in the root (Assets) folder of your project
- pragma

You can read more about it here: https://issuetracker.unity3d.com/issues/serializedfield-fields-produce-field-is-never-assigned-to-dot-dot-dot-warning

**Comment by Mathijs-Bakker** [comment]
@Suvitruf Completely off-topic... 
I can't read any of this stuff... But I played this game (and it's successor Flashback) multiple times. And yes also on the A500. 
https://suvitruf.ru/2020/01/07/7465/another_world_polygons_amiga500/

Are you creating anything like this yourself? If yes then give a yell when we can play it.
(and if it has Zenject under the hood, I will add it to 'Made with Zenject' section)

Btw. I am closing this issue as your question has been answered.
