### ISSUE TITLE
Race conditions in some mac?

### ISSUE THREAD

**Issue by SwingWren** [modesttree/Zenject#67]
I'm having some issues in some mac devices where it seems that the awake is executed before the injection to the monobehaviour classes. I've checked the execution order of zenject and its ordered correctly. Is this possible? Are there any cases where this could be happening?

**Comment by Mathijs-Bakker** [comment]
With the way Unity executes the events, it can be possible. And it is something you have little control over. 
You checked the Zenject's execution order, so Project/Scene kernel and scene context are on top.

You write: on some Macs you have this issue. Which means on others you don't?
Is this at random? Or device specific? (diff MacOS versions)
Which Unity version does your project run? And Scripting backend? Mono or IL2CPP?

I know you have read these pages but still post them for references:
https://github.com/svermeulen/Extenject#zenject-order-of-operations
https://github.com/svermeulen/Extenject#general-guidelines--recommendations--gotchas--tips-and-tricks

This is all I can think of right now. ... maybe something crosses my mind later.

**Comment by SwingWren** [comment]
Hello! Thanks for the quick reply. After looking trough the logs it all points out the source of the problem is an instantiation of an object that fails in the GameInstaller and makes Zenject stop injecting stuff thus making stuff not there in Unity Awake.
So no related to Zenject.

thanks for the help anyway :)
