### ISSUE TITLE
Unity Addressable Assets

### ISSUE THREAD

**Issue by ajon542** [modesttree/Zenject#8]
During installation, we have a number of prefabs that are installed in the scene context. The problem with referencing prefabs in the scene is any assets that are referenced are included in the final build regardless of whether they are marked to be in an asset bundle or not. Ideally, we do not want to have any references to prefabs in the scene but still want to be able to install it somehow. Unity addresses the prefab reference with addressable assets which is still a preview package. Are there any plans to support binding from addressable assets? Does Extenject support something similar currently that we could utilize with just asset bundles?

**Comment by ajon542** [comment]
As a quick test, I tried providing my own IPrefabProvider and that seemed to work for synchronous loading of assets but have yet to find a way to handle async loading of asset bundles.

`

    public class AssetBundlePrefabProvider : IPrefabProvider
    {
        private readonly string _assetBundleName;
        private readonly string _prefabName;
        private GameObject _prefab;
        
        public AssetBundlePrefabProvider(string assetBundleName, string prefabName)
        {
            _assetBundleName = assetBundleName;
            _prefabName = prefabName;
        }
    
        public UnityEngine.Object GetPrefab()
        {
            if (_prefab == null)
            {
                var assetBundle = LoadAssetBundle(_assetBundleName);
                _prefab = assetBundle.LoadAsset<GameObject>(_prefabName);   
            }
            
            return _prefab;
        }
        
        private AssetBundle LoadAssetBundle(string assetBundleName)
        {
            var assetBundle =
                AssetBundle.LoadFromFile(System.IO.Path.Combine(Application.streamingAssetsPath, assetBundleName));
        
            if (assetBundle == null)
            {
                throw new System.Exception($"could not load asset bundle with name {assetBundleName}");
            }
            return assetBundle;
        }
    }
`

**Comment by svermeulen** [comment]
Yeah, we could add bindings that use something like your `AssetBundlePrefabProvider` and add methods like FromPrefabAssetBundle, etc.  That would make sense.  But I don't see how we could make it async.  Bindings have to be synchronous.  

If you want to load it asynchronously then you'd have to do that yourself and then pass the result to zenject.

**Comment by svermeulen** [comment]
In terms of addressable assets, I'm not really sure.  I haven't played with it yet.  But we could certainly add it as an alternative to prefabs when it's ready

**Comment by quinnhoener** [comment]
I found this: https://groups.google.com/forum/#!topic/zenject/Qc8Lq26bWKs

And also this: https://forum.unity.com/threads/zenject-dependency-injection-framework-for-unity.201184/#post-2361771

Which mentions using an IEnumerator to await loading on the Create() method of your factory. Is this still supported? All addressables use Async loading, so you could try to wait for your response before returning similar to those examples. 

I'm using addressables now as well and will let you know how my experience goes. In a very similar situation to @ajon542

**Comment by yacuzo** [comment]
Sounds to me like a good case for an AsyncPlaceholderFactory<> (same as usual, but the .Create() method is async) with a .FromAssertBundlePrefab() binding. 

I have wanted an async factory for some time, due to cases where we load raw meshes for models from a server.
