### ISSUE TITLE
is it okay to use Extenject unity 2020 and ilcpp2 ios build ?(only use bind install Field injection)

### ISSUE THREAD

**Issue by ghost** [modesttree/Zenject#85]
> **Note:** Please don't file an issue to ask a question. You'll get faster results by using the resources below.

:rocket: **Chat (recommended):**
* [Extenject community on Gitter](https://gitter.im/Extenject/community) (Official)
* [Infallible Code's Discord](https://discord.gg/T5y5TD) (has an #Extenject-Zenject channel)

:snail: **Websites/forums:**
* [StackOverflow](https://stackoverflow.com/questions/tagged/zenject)
* [Unity Forums](https://forum.unity.com/threads/zenject-dependency-injection-framework-for-unity.201184/)

**Comment by Mathijs-Bakker** [comment]
Yes it **should** be OK. But it has **not** been tested.
Simply because Unity 2020 is not officially released (it's current state is still *alpha*).

**Comment by ghost** [comment]
Okay thanks happy 2020~
