### ISSUE TITLE
Interface Support for Signals

### ISSUE THREAD

**Issue by Extrys** [modesttree/Zenject#90]
**Is your feature request related to a problem? Please describe.**
Declaring Concrete signal types 
make posible just subscribing to that concrete type
so i can not normally subscribe to interfaces of fired signals

**Describe the solution you'd like**
What i want is to declare the signals in a way that it's interfaces do it too
and when i fire the concrete signal, interfaces declarations do it too

**Describe alternatives you've considered**
just working normally coupling the concrete types to the subscriptors

**Comment by Extrys** [comment]
#91 Resolves this issue

**Comment by Mathijs-Bakker** [comment]
Continuous Integration workflow is running smoothly. It will now run the tests from the test suite and create Unity builds for all the supported targets.

You can now do your PR again.

Cheers!
